overrides:
- chosen_priority: Slack経由でクライアントに確認が必要
  conflict_group: cpa_vs_volume
  decided_at: '2026-04-30T17:40:08.502550'
  decided_by: pending
  expires_at: '2026-07-29T17:40:08.502550'
- chosen_priority: Slack経由でクライアントに確認が必要
  conflict_group: learning_vs_testing
  decided_at: '2026-04-30T17:39:47.807664'
  decided_by: pending
  expires_at: '2026-07-29T17:39:47.807664'
version: '1.0'
